//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class female_billionaires
    {
        public int No { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Net_worth { get; set; }
        public string Citizenship { get; set; }
        public Nullable<int> World_rank { get; set; }
    }
}
